[package]
name = "mfa-archive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
mfa-config = { path = "../mfa-config" }
mfa-contracts = { path = "../mfa-contracts" }
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
