[package]
name = "mfa-dashboard-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mfa-analytics = { path = "../mfa-analytics" }
mfa-contracts = { path = "../mfa-contracts" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
semver.workspace = true
tokio.workspace = true
